runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /
  static_files: /img
  upload: /img

- url: /(.*)
  static_files: \1
  upload: (.*)
